- Fixed error "ICE plugin init: TypeError: sel.nativeSelection is null" on loading CKEditor - Reworked demo.js to initially set ckeditor data to value which helps to reproduce the bug "'ice.dom.remove is not a function' error occurs when clicking on 1. Ctrl+A, 2. Del buttons on ckeditor control" - Fixed 'ice.dom.remove is not a function' error when clicking on 1. Ctrl+A, 2. Del buttons on ckeditor control